### ISSUE TITLE
Add support for SessionProvider

### ISSUE THREAD

**Issue by jjdonov** [AppXpress/axus#3]
The SessionProvider object lets the developer access runtime information about the current user and the current organization.
- `public String getCurrentUserId();` - returns the User ID of the person logged into the system.
- `public String getCurrentOrgId();` - returns the Organization ID that the person logged into the system belongs to.
- `public String getCurrentOrgName();` - returns the Organization Name that the person logged into the system belongs to.
- `public Set<String> getCurrentOrgRoles();` - returns all of the roles that are played in this transaction by the Organization that the person logged into the system belongs to. For example, if the transaction is anchored to an Order, the roles this org plays in the Order will also be returned.

For more information see [the developer network](http://developer.gtnexus.com/appxpress-modules/scripting/providers/current-user-and-organization)

**Comment by sbendfelt** [comment]
code committed to session-provider feature
